### ISSUE TITLE
transformers

### ISSUE THREAD

**Issue by spiderslave** [buttshock/buttshock-et312-schematics#1]
The suggested part for T2 & T3 (wurth 750811048) appears to be the reverse of what you want. (high voltage on the centre tapped side)
My googlefoo isn't strong enough to find an appropriate replacement :(

**Comment by qdot** [comment]
On our mk312-bt box (https://github.com/metafetish/mk312-bt), we use 42TL004-RC transformers as the replacement:

https://www.mouser.com/ProductDetail/Xicon/42TL004-RC/?qs=%252bLh6ltJumVRX87vpOY3zCA%3D%3D

You might want to check out that repo for updated schematics, as we can't even source the Wurth these days.

**Comment by qdot** [comment]
Closing, as this repo is being deprecated in preference to using the mk312-bt repo.
