### ISSUE TITLE
Several issues with the current version of the schematic

### ISSUE THREAD

**Issue by chrissbg** [buttshock/buttshock-et312-schematics#2]
Hi, I had a look at the schematic and by comparing with the hand-written notes found a few issues:
1.) C11 should be 1n instead of 1u
2.) R43 should be 100k instead of 20k
3.) R49 should be 47k instead of 4k7
4.) Q3 and Q6 should be p-channel MOSFETs instead of n-channel

**Comment by qdot** [comment]
These got drawn but never really updated after that (I'll put that info in the README). Check out https://github.com/buttshock/mk312-bt, there's updated schematics there for boards that've actually been manufactured.

**Comment by qdot** [comment]
Closing, as this repo is being deprecated in preference to using the mk312-bt repo.
